=== BrendonHenrique/MedUmiWeb-Back-end/target/WebCalMedUmi-3.0/WEB-INF/classes/utils/schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "pontos",
    "description": "coordenadas de calibração",
    "type": "array",

    "items": {
        "type": "object",
        "required":["x","y","xReajustado","habilitado"],
        "properties": {
            "x": {
                "description": "Coordenada representada pelas amostras da garten",
                "type": "string"
            },
            "y": {
                "description": "Coordenada representada pelas amostras do laboratório",
                "type": "string"
            },
            "habilitado": {
                "description": "Booleano responsável por mostrar ou não no gráfico",
                "type": "boolean"
            },
            "xReajustado": {
                "description": "Coordenada das amostras garten reajustadas utilizando a equação inversa",
                "type": "number"
            }
        }
    }
}

=== BrendonHenrique/MedUmiWeb-Back-end/target/classes/utils/data.json
[{
    "x": "12",
    "y": "230",
    "habilitado": true,
    "xReajustado": 12
}, {
    "x": "011",
    "y": "022",
    "habilitado": true,
    "xReajustado": 11
}, {
    "x": "12",
    "y": "023",
    "habilitado": true,
    "xReajustado": 12
}, {
    "x": "2",
    "y": "3",
    "habilitado": true,
    "xReajustado": 2
}, {
    "x": "12",
    "y": "32",
    "habilitado": true,
    "xReajustado": 12
}, {
    "x": "1",
    "y": "2",
    "habilitado": true,
    "xReajustado": 1
}, {
    "x": "22",
    "y": "33",
    "habilitado": true,
    "xReajustado": 22
}, {
    "x": "12",
    "y": "23",
    "habilitado": true,
    "xReajustado": 12
}]
